# Docker compose postgres 14
version: '3'
services:
  postgres:
    image: postgres:14.7
    container_name: anylist-postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data